# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 387)
        Dialog.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.CLASS_COMBO = QtWidgets.QComboBox(Dialog)
        self.CLASS_COMBO.setGeometry(QtCore.QRect(20, 40, 191, 22))
        self.CLASS_COMBO.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.CLASS_COMBO.setObjectName("CLASS_COMBO")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.SUBMIT_BUTT = QtWidgets.QPushButton(Dialog)
        self.SUBMIT_BUTT.setGeometry(QtCore.QRect(260, 20, 91, 41))
        self.SUBMIT_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SUBMIT_BUTT.setObjectName("SUBMIT_BUTT")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(20, 60, 341, 311))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.ENTER_FRONT = QtWidgets.QPlainTextEdit(self.widget)
        self.ENTER_FRONT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ENTER_FRONT.setObjectName("ENTER_FRONT")
        self.verticalLayout.addWidget(self.ENTER_FRONT)
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.ENTER_BACK = QtWidgets.QPlainTextEdit(self.widget)
        self.ENTER_BACK.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ENTER_BACK.setObjectName("ENTER_BACK")
        self.verticalLayout.addWidget(self.ENTER_BACK)
        self.label.raise_()
        self.label_2.raise_()
        self.ENTER_FRONT.raise_()
        self.CLASS_COMBO.raise_()
        self.SUBMIT_BUTT.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select class:"))
        self.SUBMIT_BUTT.setText(_translate("Dialog", "Submit"))
        self.label_2.setText(_translate("Dialog", "Front:"))
        self.label_3.setText(_translate("Dialog", "Back:"))
