# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 173)
        Dialog.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.ADD_BUTT = QtWidgets.QPushButton(Dialog)
        self.ADD_BUTT.setGeometry(QtCore.QRect(140, 120, 121, 23))
        self.ADD_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ADD_BUTT.setObjectName("ADD_BUTT")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ENTER_CLASS = QtWidgets.QPlainTextEdit(Dialog)
        self.ENTER_CLASS.setGeometry(QtCore.QRect(80, 50, 241, 41))
        self.ENTER_CLASS.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.ENTER_CLASS.setObjectName("ENTER_CLASS")
        self.ERROR_LABEL = QtWidgets.QLabel(Dialog)
        self.ERROR_LABEL.setGeometry(QtCore.QRect(280, 100, 111, 61))
        self.ERROR_LABEL.setObjectName("ERROR_LABEL")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.ADD_BUTT.setText(_translate("Dialog", "Add Class"))
        self.label.setText(_translate("Dialog", "Enter new class name:"))
        self.ERROR_LABEL.setText(_translate("Dialog", "  "))
