# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'practice.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(724, 465)
        Dialog.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.MAIN_LABEL = QtWidgets.QLabel(Dialog)
        self.MAIN_LABEL.setGeometry(QtCore.QRect(90, 30, 531, 281))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.MAIN_LABEL.setFont(font)
        self.MAIN_LABEL.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.MAIN_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.MAIN_LABEL.setObjectName("MAIN_LABEL")
        self.HINT_BUTT = QtWidgets.QPushButton(Dialog)
        self.HINT_BUTT.setGeometry(QtCore.QRect(300, 400, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.HINT_BUTT.setFont(font)
        self.HINT_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.HINT_BUTT.setObjectName("HINT_BUTT")
        self.HINT_LABEL = QtWidgets.QLabel(Dialog)
        self.HINT_LABEL.setGeometry(QtCore.QRect(200, 380, 321, 71))
        self.HINT_LABEL.setStyleSheet("background-color: rgb(232, 232, 232);")
        self.HINT_LABEL.setText("")
        self.HINT_LABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.HINT_LABEL.setObjectName("HINT_LABEL")
        self.NEXT_BUTT = QtWidgets.QPushButton(Dialog)
        self.NEXT_BUTT.setGeometry(QtCore.QRect(580, 340, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NEXT_BUTT.setFont(font)
        self.NEXT_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NEXT_BUTT.setObjectName("NEXT_BUTT")
        self.PREV_BUTT = QtWidgets.QPushButton(Dialog)
        self.PREV_BUTT.setGeometry(QtCore.QRect(40, 340, 101, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PREV_BUTT.setFont(font)
        self.PREV_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.PREV_BUTT.setObjectName("PREV_BUTT")
        self.FLIP_BUTT = QtWidgets.QPushButton(Dialog)
        self.FLIP_BUTT.setGeometry(QtCore.QRect(290, 330, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FLIP_BUTT.setFont(font)
        self.FLIP_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FLIP_BUTT.setObjectName("FLIP_BUTT")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.MAIN_LABEL.setText(_translate("Dialog", "text"))
        self.HINT_BUTT.setText(_translate("Dialog", "See Hint"))
        self.NEXT_BUTT.setText(_translate("Dialog", "Next"))
        self.PREV_BUTT.setText(_translate("Dialog", "Previous"))
        self.FLIP_BUTT.setText(_translate("Dialog", "Flip!"))
