# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'removeCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 129)
        Dialog.setStyleSheet("background-color: rgb(176, 176, 176);")
        self.CLASS_COMBO = QtWidgets.QComboBox(Dialog)
        self.CLASS_COMBO.setGeometry(QtCore.QRect(20, 30, 271, 22))
        self.CLASS_COMBO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CLASS_COMBO.setObjectName("CLASS_COMBO")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.CARD_COMBO = QtWidgets.QComboBox(Dialog)
        self.CARD_COMBO.setGeometry(QtCore.QRect(20, 80, 271, 22))
        self.CARD_COMBO.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CARD_COMBO.setObjectName("CARD_COMBO")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.SUBMIT_BUTT = QtWidgets.QPushButton(Dialog)
        self.SUBMIT_BUTT.setGeometry(QtCore.QRect(310, 80, 75, 31))
        self.SUBMIT_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SUBMIT_BUTT.setObjectName("SUBMIT_BUTT")
        self.SELECT_CLASS_BUTT = QtWidgets.QPushButton(Dialog)
        self.SELECT_CLASS_BUTT.setGeometry(QtCore.QRect(310, 20, 75, 31))
        self.SELECT_CLASS_BUTT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.SELECT_CLASS_BUTT.setObjectName("SELECT_CLASS_BUTT")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Select class:"))
        self.label_2.setText(_translate("Dialog", "Select card to delete:"))
        self.SUBMIT_BUTT.setText(_translate("Dialog", "Submit"))
        self.SELECT_CLASS_BUTT.setText(_translate("Dialog", "Select Class"))
